# https://blowfish.page/docs/getting-started/
theme = "github.com/nunocoracao/blowfish/v2"

title = "arvimal.github.io"  
copyright = "Copyright © 2008–2023, Vimal A.R; all rights reserved."

baseurl = "https://arvimal.github.io/"  # Include trailing slash

languageCode = "en"

paginate = 10
summaryLength = 0

# introDescription = "yes"
# description = "yes"
usePageBundles = "yes"

