title = "arvimal.github.io"

[params.author]
name = "Vimal A R"
image = "images/avatar.jpg"
headline = "SRE | Linux | Open Source"
bio = "Still figuring it out!"
links = [
  { linkedin = "https://linkedin.com/in/arvimal" },
  { github = "https://github.com/arvimal" }
]
