# https://imfing.github.io/hextra/docs/getting-started/

theme = "system"  # system, dark, or light

[navbar]
  displayTitle = true
  displayLogo = true
  [navbar.logo]
    path = "images/logo.png"
    dark = "images/logo.png"

[footer]
  displayCopyright = true
  displayPoweredBy = false

displayUpdatedDate = true
dateFormat = "January 2, 2006"

[page]
  width = "normal"

[search]
  enable = true
  type = "flexsearch"

[editURL]
  enable = false

[blog]
  list.displayTags = true
  list.sortBy = "date"
  list.sortOrder = "desc"
