# https://blowfish.page/docs/configuration/

[global]
colorScheme = "autumn"
smartTOC = "true"
enableSearch = "true"
autoSwitchAppearance = "true"
enableCodeCopy = "true"

[header]
layout = "basic"

[homepage]
layout = "background"
homepageImage = "images/will-africano-s4a29qbHssg.jpg"
cardView = "true"


[article]
showViews = "true"
showLikes = "true"
showDateUpdated = "true"
showHero = "true"
heroStyle = "background"
showTableOfContents = "true"
showRelatedContent = "true"
relatedContentLimit = 3

