# https://blowfish.page/docs/configuration/

[global]
colorScheme = "autumn"
smartTOC = "true"
enableSearch = "true"
autoSwitchAppearance = "true"
enableCodeCopy = "true"

[header]
layout = "basic"

[homepage]
layout = "background"
homepageImage = "images/scott-rodgerson-lRtzEExP0H8.jpg"


