# https://jpanther.github.io/congo/docs/configuration/

colorScheme = "ocean"
defaultAppearance = "dark"
autoSwitchAppearance = true
enableSearch = true
enableCodeCopy = true
mainSections = ["posts"]

[homepage]
  layout = "card"
  showRecent = true
  showRecentItems = 8

[article]
  showDate = true
  showDateUpdated = true
  showTableOfContents = true
  showReadingTime = true
  showRelatedContent = true
  relatedContentLimit = 3
  showEdit = false

[list]
  showSummary = true
  groupByYear = true
