# config/_default/menus.toml

[[main]]
  name = "Blog"
  pageRef = "posts/"
  weight = 10


[[main]]
  pre = "github"
  name = "GitHub"
  url = "https://github.com/arvimal"
  weight = 30

[[main]]
  name = "LinkedIn"
  url = "https://linkedin.com/in/arvimal"
  weight = 40

[[main]]
  name = "About"
  pageRef = "about"
  weight = 50

[[main]]
  name = "RSS"
  title = "rss"
  weight = 60
  pageRef = "public/index.xml"

